name: trading-signals
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - plotly>=5.15.0
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - joblib>=1.3.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.0.0
  - flake8>=6.0.0
  - isort>=5.12.0
  - pip
  - pip:
    - yfinance>=0.2.20
    - TA-Lib>=0.4.25
    - ta>=0.10.2
    - SQLAlchemy>=2.0.0
    - typer>=0.9.0
